compatibility_date: 2026-06-24
build:
  shopwareVersionConstraint: ">=6.6.10.18 <6.8.0"
  zip:
    composer:
      enabled: true
    assets:
      enabled: true
    pack:
      excludes:
        paths:
          - .github
          - .tools
          - dist
          - tests
          - Dockerfile
          - docker-compose.yml
